/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author noito_000
 */
public class FinanzplanPanel extends javax.swing.JPanel {

    /**
     * Creates new form FinanzplanPanel
     */
    private DetailContainer dc;
    private String name;
    private ResultSet result;
    private Statement st;
    private int id;
    
    public FinanzplanPanel(DetailContainer dc) {
        this.dc = dc;
        initComponents();
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public void callDb() {
        try {
            st = this.dc.getOracleConnector().dbcon.createStatement();
            
            result = st.executeQuery("select a.geplant, a.vorhanden, a.ausgegeben, a.hj, a.verwnachweis" +
                    ", d.name, a.idfinplan from finanzplan a, baustatus b, baumassnahme c, foerderprogramm d"+
                    " where c.name = '"+name+"' and c.idmassnahme=b.baumassnahme_idmassnahme"+
                    " and a.baustatus_idstatus=b.baumassnahme_idmassnahme and "+
                    "a.foerderprogramm_idfprogramm=d.idfprogramm");
            while(result.next()){ 
                this.jTextField1.setText(result.getString(1));
                this.jLabel3.setText(result.getString(2));
                this.jTextField6.setText(result.getString(3));
                this.jTextField2.setText(result.getString(4));
                this.jLabel2.setText(result.getString(6));
                this.jTextArea1.setText(result.getString(5));
                id = result.getInt(7);
            }
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(MitarbeiterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Finanzplan");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(7, 2));

        jLabel4.setText("Geplant");
        jPanel1.add(jLabel4);

        jTextField1.setText("Geplant");
        jPanel1.add(jTextField1);

        jLabel5.setText("Vorhanden");
        jPanel1.add(jLabel5);

        jLabel3.setText("Vorhanden");
        jPanel1.add(jLabel3);

        jLabel6.setText("Ausgegeben");
        jPanel1.add(jLabel6);

        jTextField6.setText("Ausgegeben");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6);

        jLabel7.setText("Haushaltsjahr");
        jPanel1.add(jLabel7);

        jTextField2.setText("Haushaltsjahr");
        jPanel1.add(jTextField2);

        jLabel8.setText("Förderprogramm");
        jPanel1.add(jLabel8);

        jLabel2.setText("Foerderprogramm");
        jPanel1.add(jLabel2);

        jLabel9.setText("Verwendungs Nachweis");
        jPanel1.add(jLabel9);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Verwendungs Nachweis\n");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        jButton2.setText("Abbrechen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setText("Graphik");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jPanel1.add(jPanel2);

        jButton1.setText("Speichern");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dc.changeActive(name+KonstantenKlassen.ConstantStrings.SEPARATOR+KonstantenKlassen.ConstantStrings.SUMMARY);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            st = this.dc.getOracleConnector().dbcon.createStatement();
            int i = st.executeUpdate("update finanzplan a set a.geplant='"+this.jTextField1.getText()+"', "+
                    "a.ausgegeben='"+this.jTextField6.getText()+"', a.hj='"+this.jTextField2.getText()+
                    "', a.verwnachweis='"+this.jTextArea1.getText()+"' where a.idfinplan="+id+"");
            dc.changeActive(name+KonstantenKlassen.ConstantStrings.SEPARATOR+KonstantenKlassen.ConstantStrings.SUMMARY);
        } catch (SQLException ex) {
            Logger.getLogger(MitarbeiterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dc.changeActive(id+KonstantenKlassen.ConstantStrings.SEPARATOR+"FinanzChart");
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
