/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;


import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYDotRenderer;
import org.jfree.data.xy.*;

/**
 *
 * @author Marco
 */
public class FinanzPanel extends javax.swing.JPanel {

    /**
     * Creates new form FinanzPanel
     */
    private DefaultXYDataset dataset;
    private NumberAxis yax;
    private NumberAxis xax;
    private XYDotRenderer dot;
    private double [][] A = {{1,2,5},{3,4,0}};
    private XYPlot plot;
    private JFreeChart chart1;
    private ChartPanel chartPanel2;
    
    public FinanzPanel() {
        initComponents();
        

    dataset = new DefaultXYDataset();
    dataset.addSeries("xy", A);    // A wird unter dem Namen xy abgespeichert
    dot = new XYDotRenderer();
    dot.setDotHeight(5);
    dot.setDotWidth(5);
    xax = new NumberAxis("x");
    yax = new NumberAxis("y"); 
    plot = new XYPlot(dataset,xax,yax, dot);
    chart1 = new JFreeChart(plot);
    chartPanel2 = new ChartPanel(chart1);
    this.add(chartPanel2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
