/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

/**
 *
 * @author Marco
 */
public class NaviPanel extends javax.swing.JPanel {

    /**
     * Creates new form NaviPanel
     */
    
    
    public NaviPanel() {
        initComponents();
    }
    
    public void initTree(Start.OracleConnector con){
        this.con = con;
        treePanel1.initTree(con);
    }
    
    public TreePanel getTree(){
        return this.treePanel1;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        treePanel1 = new Panels.TreePanel();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new java.awt.BorderLayout());
        add(treePanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Panels.TreePanel treePanel1;
    // End of variables declaration//GEN-END:variables
    private Start.OracleConnector con;
}

