/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author noito_000
 */
public class ObjektPanel extends javax.swing.JPanel {

    /**
     * Creates new form ObjektPanel
     */
    private DetailContainer dc;
    private String name;
    private String projekt;
    private ResultSet result;
    private Statement st;
    
    public ObjektPanel(DetailContainer dc) {
        this.dc = dc;
        initComponents();
    }

     public void setName(String name, String projekt) {
        this.projekt = projekt;
        this.name = name;
    }
    
    public void callDb() {
        try {
            st = this.dc.getOracleConnector().dbcon.createStatement();
            
            result = st.executeQuery("select a.name, a.adresse, a.liegenschaft, a.eigentuemer, a.kategorie\n" +
"from objekt a\n" +
"where a.name = '"+name+"'");
            while(result.next()){
                this.jTextField2.setText(result.getString(1));
                this.jTextField3.setText(result.getString(2));
                this.jTextField4.setText(result.getString(3));
                this.jTextField5.setText(result.getString(4));
            }
        } catch (SQLException ex) {
            Logger.getLogger(MitarbeiterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Objekt");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(6, 0));

        jTextField2.setText("Name");
        jPanel1.add(jTextField2);

        jTextField3.setText("Adresse");
        jPanel1.add(jTextField3);

        jTextField4.setText("Liegenschaft");
        jPanel1.add(jTextField4);

        jTextField5.setText("Eigentümer");
        jPanel1.add(jTextField5);

        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        jButton2.setText("Abbrechen");
        jPanel2.add(jButton2);

        jButton3.setText("Reset");
        jPanel2.add(jButton3);

        jButton1.setText("Speichern");
        jPanel2.add(jButton1);

        jPanel1.add(jPanel2);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
