/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Marco
 */
public class StatusPanel extends javax.swing.JPanel {

    /**
     * Creates new form StatusPanel
     */
    private DetailContainer dc;
    private String name;
    private ResultSet result;
    private Statement st;
    private int id;
    
    public StatusPanel(DetailContainer dc) {
        this.dc = dc;
        initComponents();
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public void callDb() {
        try {
            st = this.dc.getOracleConnector().dbcon.createStatement();
            
            result = st.executeQuery("select a.fertig, a.plstand, a.dfstand, a.notizen"+
                    " ,a.idstatus from baustatus a, baumassnahme b where b.name='"+name+"' and"+
                    " b.idmassnahme=a.baumassnahme_idmassnahme");
            while(result.next()){ 
                this.jTextField1.setText(result.getString(1));
                this.jTextArea3.setText(result.getString(2));
                this.jTextArea1.setText(result.getString(3));
                this.jTextArea2.setText(result.getString(4));
                id = result.getInt(5);
                              
            }
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(MitarbeiterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(5, 4));

        jLabel1.setText("Fertig");
        add(jLabel1);

        jTextField1.setText("jahr");
        add(jTextField1);

        jLabel2.setText("Planungsstand");
        add(jLabel2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("?");
        jScrollPane3.setViewportView(jTextArea3);

        add(jScrollPane3);

        jLabel3.setText("Durchführungsstand");
        add(jLabel3);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("?\n");
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);

        jLabel4.setText("Notizen");
        add(jLabel4);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("?");
        jScrollPane2.setViewportView(jTextArea2);

        add(jScrollPane2);

        jButton1.setText("Abbrechen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);

        jButton2.setText("Speichern");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dc.changeActive(name+KonstantenKlassen.ConstantStrings.SEPARATOR+KonstantenKlassen.ConstantStrings.SUMMARY);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            st = this.dc.getOracleConnector().dbcon.createStatement();
            int i = st.executeUpdate("update baustatus set fertig='"+this.jTextField1.getText()+"', "+
                    "plstand='"+this.jTextArea3.getText()+"', dfstand='"+this.jTextArea1.getText()+
                    "', notizen='"+this.jTextArea2.getText()+"' where idstatus="+id+"");
            dc.changeActive(name+KonstantenKlassen.ConstantStrings.SEPARATOR+KonstantenKlassen.ConstantStrings.SUMMARY);
        } catch (SQLException ex) {
            Logger.getLogger(MitarbeiterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
